const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Keyboard,
		C3.Behaviors.scrollto,
		C3.Behaviors.MoveTo,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Json,
		C3.Plugins.Share,
		C3.Plugins.Browser,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Behaviors.Bullet,
		C3.Plugins.Particles,
		C3.Behaviors.Pin,
		C3.Plugins.NinePatch,
		C3.Behaviors.wrap,
		C3.Plugins.TextBox,
		C3.Plugins.Button,
		C3.Plugins.Touch,
		C3.Plugins.MetaproPlugin,
		C3.Plugins.HTMLElement,
		C3.Behaviors.Rotate,
		C3.Behaviors.bound,
		C3.Behaviors.Flash,
		C3.Behaviors.custom,
		C3.Behaviors.Fade,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.MetaproPlugin.Acts.MultipleReadContract,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.MetaproPlugin.Cnds.OnMultipleReadContractDataReceived,
		C3.Plugins.Json.Acts.SetJSON,
		C3.Plugins.MetaproPlugin.Exps.GetLastMultipleReadContractData,
		C3.ScriptsInEvents.Ecarshop_Event70_Act2,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.MetaproPlugin.Acts.SendContractTransaction,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.MetaproPlugin.Cnds.OnTransactionSent,
		C3.ScriptsInEvents.Ecarshop_Event74_Act1,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.MetaproPlugin.Acts.SetTransactionStatus,
		C3.Plugins.MetaproPlugin.Cnds.OnReadContractDataReceived,
		C3.Plugins.MetaproPlugin.Exps.GetLastReadContractData,
		C3.Plugins.MetaproPlugin.Acts.ReadContract,
		C3.Plugins.MetaproPlugin.Cnds.OnError,
		C3.Plugins.MetaproPlugin.Exps.GetLastError,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.MetaproPlugin.Exps.GetTransactionStatus,
		C3.ScriptsInEvents.Ecarshop_Event83_Act1,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.ScriptsInEvents.Emainmenu_Event25_Act1,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.MetaproPlugin.Acts.SendCrypto,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.MetaproPlugin.Acts.AddScore,
		C3.Plugins.MetaproPlugin.Acts.Login,
		C3.Plugins.MetaproPlugin.Cnds.OnUserLoggedIn,
		C3.Plugins.MetaproPlugin.Exps.GetUsername,
		C3.Plugins.MetaproPlugin.Exps.GetAccount,
		C3.Plugins.MetaproPlugin.Acts.RequestBestScore,
		C3.Plugins.MetaproPlugin.Exps.GetBestScore,
		C3.Plugins.MetaproPlugin.Acts.RequestUserScore,
		C3.Plugins.MetaproPlugin.Exps.GetDynamicReward,
		C3.Plugins.MetaproPlugin.Exps.GetTotalScore,
		C3.Plugins.MetaproPlugin.Acts.RequestNumberOfRuns,
		C3.Plugins.MetaproPlugin.Exps.GetNumberOfRuns,
		C3.Plugins.MetaproPlugin.Acts.FetchReferralCode,
		C3.Plugins.MetaproPlugin.Exps.GetAvatar,
		C3.Plugins.MetaproPlugin.Cnds.OnReferralCodeEmpty,
		C3.Plugins.MetaproPlugin.Acts.GenerateReferralCode,
		C3.Plugins.MetaproPlugin.Exps.GetReferralCode,
		C3.Plugins.MetaproPlugin.Cnds.OnReferralCodeExists,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.MetaproPlugin.Acts.CheckReferralCodeFromDeeplink,
		C3.Plugins.MetaproPlugin.Cnds.OnRefCodeFromDeeplinkExists,
		C3.Plugins.MetaproPlugin.Exps.GetRefCodeFromDeeplink,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.MetaproPlugin.Acts.RequestAccount,
		C3.Plugins.MetaproPlugin.Cnds.OnAccountReceived,
		C3.Plugins.MetaproPlugin.Acts.CheckIfRegistered,
		C3.Plugins.MetaproPlugin.Cnds.OnIsRegistered,
		C3.Plugins.MetaproPlugin.Cnds.OnIsNotRegistered,
		C3.Plugins.HTMLElement.Acts.SetContent,
		C3.Plugins.MetaproPlugin.Cnds.OnUsernameUpdated,
		C3.Plugins.MetaproPlugin.Acts.UpdateUsername,
		C3.Plugins.MetaproPlugin.Acts.RequestBestScoresLeaderboardByMapId,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.MetaproPlugin.Cnds.OnBestScoresLeaderboardReceived,
		C3.Plugins.MetaproPlugin.Exps.GetBestScoresLeaderboard,
		C3.Plugins.Json.Exps.ToBeautifiedString,
		C3.Plugins.Json.Cnds.ForEach,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Json.Cnds.HasKey,
		C3.Plugins.MetaproPlugin.Acts.RequestReferralStructure,
		C3.Plugins.MetaproPlugin.Acts.RequestReferralLeaderboard,
		C3.Plugins.MetaproPlugin.Exps.GetLeaderboardId,
		C3.Plugins.MetaproPlugin.Exps.GetLeaderboardApiKey,
		C3.ScriptsInEvents.Efriends_Event3_Act3,
		C3.Plugins.Share.Acts.Share,
		C3.Plugins.MetaproPlugin.Exps.GetPlatformId,
		C3.Plugins.MetaproPlugin.Cnds.OnReferralStructureReceived,
		C3.Plugins.MetaproPlugin.Exps.GetReferralStructure,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.fps,
		C3.Plugins.System.Exps.objectcount,
		C3.Behaviors.custom.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Flash.Cnds.OnFlashEnded,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.TiledBg.Cnds.CompareY,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Acts.SetTimescale
	];
};
self.C3_JsPropNameTable = [
	{SpeedMargin: 0},
	{Keyboard: 0},
	{ScrollTo: 0},
	{MoveTo: 0},
	{CameraCenter: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{JSON: 0},
	{Share: 0},
	{Browser: 0},
	{TouchOffsetY: 0},
	{FlashSequence: 0},
	{Car0: 0},
	{Car1: 0},
	{Car2: 0},
	{Car3: 0},
	{Car4: 0},
	{Car5: 0},
	{Car6: 0},
	{Car7: 0},
	{Sine: 0},
	{Tree: 0},
	{Stone: 0},
	{Tunnel: 0},
	{Tunnel2: 0},
	{RandomX: 0},
	{TreeRandomX: 0},
	{RockPile: 0},
	{Lake2: 0},
	{DebugText: 0},
	{PauseBtn: 0},
	{CoinsText: 0},
	{CoinsIcon: 0},
	{CheckpointsIcon: 0},
	{CheckpointsText: 0},
	{TimeIcon: 0},
	{TimeText: 0},
	{Tween: 0},
	{MenuBoosterIcon: 0},
	{StartBoosterButton: 0},
	{TimesUpText: 0},
	{TimesUpText2: 0},
	{RoadSegment0: 0},
	{RoadSegment1: 0},
	{RoadSegment2: 0},
	{RoadSegment3: 0},
	{RoadSegment4: 0},
	{RoadSegment5: 0},
	{RoadSegment6: 0},
	{RoadSegment7: 0},
	{RoadSegment8: 0},
	{RoadSegment9: 0},
	{RoadSegment10: 0},
	{RoadSegment11: 0},
	{RoadSegment12: 0},
	{RoadSegment13: 0},
	{RoadSegment14: 0},
	{RoadSegment15: 0},
	{RoadSegment16: 0},
	{RoadSegment17: 0},
	{RoadSegment18: 0},
	{RoadSegment19: 0},
	{RoadSegment20: 0},
	{RoadSegment21: 0},
	{RoadSegment22: 0},
	{RoadSegment23: 0},
	{RoadSegment24: 0},
	{RoadSegment25: 0},
	{Checkpoint: 0},
	{StartCheckpoint: 0},
	{Bullet: 0},
	{OtherCar: 0},
	{OtherCar2: 0},
	{DestroyEffect: 0},
	{CoinCollectEffect: 0},
	{OtherCar3: 0},
	{NarrowRoad: 0},
	{Road_Y: 0},
	{Road: 0},
	{Road_Y2: 0},
	{RoadWide: 0},
	{RoadEnd: 0},
	{RoadX: 0},
	{Coin1Pickup: 0},
	{TimePickup: 0},
	{MusicToggle: 0},
	{SoundsToggle: 0},
	{ButtonSmallBlackText: 0},
	{Logo: 0},
	{Pin: 0},
	{MenuCheckpointsText: 0},
	{MenuCoinsText: 0},
	{HeaderText: 0},
	{BackToMenuButtonOld: 0},
	{EndRaceText: 0},
	{SelectCarButton: 0},
	{ButtonSmallText: 0},
	{MenuCoinsIcon: 0},
	{MenuCheckpointsIcon: 0},
	{MenuSelectedCar0: 0},
	{MenuSelectedCar1: 0},
	{MenuSelectedCar2: 0},
	{MenuSelectedCar3: 0},
	{MenuSelectedCar4: 0},
	{MenuSelectedCar5: 0},
	{MenuSelectedCar6: 0},
	{MenuSelectedCar7: 0},
	{PausePanel: 0},
	{EndRaceText2: 0},
	{MenuBoosterStatusText: 0},
	{CarNameText: 0},
	{CarDetailsLabelText: 0},
	{CarDetailsText: 0},
	{CarCostText: 0},
	{ShopActiveCar: 0},
	{ShopActiveCarText: 0},
	{ButtonText: 0},
	{PanelText: 0},
	{ErrorText: 0},
	{TermsText: 0},
	{UserNameText: 0},
	{GameplaysText: 0},
	{TotalScoreText: 0},
	{LeaderboardEntryText: 0},
	{ProfilName: 0},
	{BackToMenuButton2: 0},
	{BackToMenuButton3: 0},
	{BackToMenuButton4: 0},
	{WaitHeaderText: 0},
	{SelectCarButton2: 0},
	{SelectCarButton3: 0},
	{SelectCarButton4: 0},
	{SelectCarButton5: 0},
	{SelectCarButton6: 0},
	{WaitPanel: 0},
	{WaitText: 0},
	{WaitErrorText: 0},
	{PlayButton: 0},
	{ProfileButton: 0},
	{LeaderboardButton: 0},
	{ReadyButton: 0},
	{StartButton: 0},
	{CloseEditingNameButton: 0},
	{ChangeNameButton: 0},
	{LeaderboardEntryPointsText: 0},
	{AvailableMintsText: 0},
	{CreateAccountButton: 0},
	{TokenCost: 0},
	{Wrap: 0},
	{MenuOtherCar: 0},
	{MenuOtherCar2: 0},
	{MenuOtherCar3: 0},
	{MenuOtherCar4: 0},
	{MenuOtherCar5: 0},
	{MenuOtherCar6: 0},
	{MenuRoad: 0},
	{MenuTunnel: 0},
	{Lake: 0},
	{SummaryRaceCoins: 0},
	{SummaryRacePoints: 0},
	{SummaryTopText: 0},
	{SummaryTotalCoins: 0},
	{SummaryTotalPoints: 0},
	{SummaryRestartButton: 0},
	{SummaryOKButton: 0},
	{ReferralCodeText: 0},
	{ReferralCodeTextInput: 0},
	{TermsCheckbox: 0},
	{NameInput: 0},
	{CopyCode: 0},
	{EditNameButton: 0},
	{FriendsButton: 0},
	{FriendsCode: 0},
	{FriendsLevelText: 0},
	{FriendsPercentageText: 0},
	{FriendsPointsText: 0},
	{FriendsUserCountText: 0},
	{LeaderboardRefNicknameText: 0},
	{LeaderboardRefPointsText: 0},
	{LeaderboardStart: 0},
	{ReferralsList: 0},
	{ShareLink: 0},
	{ShopDebugText: 0},
	{Sprite: 0},
	{BuyBoosterWithCoinsButton: 0},
	{BuyBoosterWithTokenButton: 0},
	{LeaderboardPointsStart: 0},
	{LeaderboardStart2: 0},
	{LeaderboardPointsStart2: 0},
	{ButtonNext: 0},
	{ButtonPrev: 0},
	{PauseMusicButton: 0},
	{PauseSoundsButton: 0},
	{Text2: 0},
	{MenuBg: 0},
	{MiddlePanel: 0},
	{ShopSetCurrentButton: 0},
	{ShopBuyButton: 0},
	{Touch: 0},
	{MetaproPlugin: 0},
	{Avatar_Profile_Main: 0},
	{LoginButton: 0},
	{ChangeCarButton: 0},
	{BackButton: 0},
	{Arrow_Right067x: 0},
	{InputBackground: 0},
	{BackToMenuButton: 0},
	{PauseResumeButton: 0},
	{PauseEndRaceButton: 0},
	{Sprite2: 0},
	{Rotate: 0},
	{Sprite3: 0},
	{TargetCircle: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{TiledBackground3: 0},
	{BoundToLayout: 0},
	{Flash: 0},
	{Cars: 0},
	{Custom2: 0},
	{Segments: 0},
	{Obstacles: 0},
	{Fade: 0},
	{FadeIn: 0},
	{ShopCars: 0},
	{CarHandling: 0},
	{CarBoosterTime: 0},
	{CarBoosterSpeedup: 0},
	{CarSpeed: 0},
	{CarCost: 0},
	{UnlockedCar0: 0},
	{UnlockedCar1: 0},
	{UnlockedCar2: 0},
	{UnlockedCar3: 0},
	{UnlockedCar4: 0},
	{UnlockedCar5: 0},
	{UnlockedCar6: 0},
	{UnlockedCar7: 0},
	{MaxMintsC1: 0},
	{MaxMintsC2: 0},
	{MaxMintsC3: 0},
	{MaxMintsC4: 0},
	{MaxMintsC5: 0},
	{MaxMintsC6: 0},
	{MaxMintsC7: 0},
	{AvailableMintsC1: 0},
	{AvailableMintsC2: 0},
	{AvailableMintsC3: 0},
	{AvailableMintsC4: 0},
	{AvailableMintsC5: 0},
	{AvailableMintsC6: 0},
	{AvailableMintsC7: 0},
	{ShopItemSelected: 0},
	{processedCarName: 0},
	{tokenIds: 0},
	{ABI: 0},
	{BATCH_OF_ABI: 0},
	{MULTICALL_ABI: 0},
	{amount: 0},
	{contractAddress: 0},
	{chainId: 0},
	{balanceOfBatchFunctionName: 0},
	{InteractionsActive: 0},
	{tokenID: 0},
	{carName: 0},
	{mintedShipName: 0},
	{BestScore: 0},
	{TotalCoins: 0},
	{BoosterAvailable: 0},
	{SelectedCar: 0},
	{OptionsMusic: 0},
	{OptionsSounds: 0},
	{rulesChecked: 0},
	{referralSettingsId: 0},
	{userName: 0},
	{userAccount: 0},
	{bestScore2: 0},
	{totalScore: 0},
	{numberOfRuns: 0},
	{userAvatarImg: 0},
	{userRefCode: 0},
	{referralCode: 0},
	{lineDelta: 0},
	{lineY: 0},
	{leaderboardLimit: 0},
	{lineYFriends: 0},
	{MoveSpeedMain: 0},
	{NextSegment: 0},
	{Paused: 0},
	{PlayerStatus: 0},
	{MoveSpeedDynamic: 0},
	{MoveSpeedBooster: 0},
	{CurrentCoins: 0},
	{CurrentPoints: 0},
	{BoosterActive: 0},
	{Timer: 0},
	{RandomColor: 0}
];

self.InstanceType = {
	SpeedMargin: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	CameraCenter: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	Share: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Car0: class extends self.ISpriteInstance {},
	Car1: class extends self.ISpriteInstance {},
	Car2: class extends self.ISpriteInstance {},
	Car3: class extends self.ISpriteInstance {},
	Car4: class extends self.ISpriteInstance {},
	Car5: class extends self.ISpriteInstance {},
	Car6: class extends self.ISpriteInstance {},
	Car7: class extends self.ISpriteInstance {},
	Tree: class extends self.ISpriteInstance {},
	Stone: class extends self.ISpriteInstance {},
	Tunnel: class extends self.ISpriteInstance {},
	Tunnel2: class extends self.ISpriteInstance {},
	TreeRandomX: class extends self.ISpriteInstance {},
	RockPile: class extends self.ISpriteInstance {},
	Lake2: class extends self.ISpriteInstance {},
	DebugText: class extends self.ITextInstance {},
	PauseBtn: class extends self.ISpriteInstance {},
	CoinsText: class extends self.ITextInstance {},
	CoinsIcon: class extends self.ISpriteInstance {},
	CheckpointsIcon: class extends self.ISpriteInstance {},
	CheckpointsText: class extends self.ITextInstance {},
	TimeIcon: class extends self.ISpriteInstance {},
	TimeText: class extends self.ITextInstance {},
	MenuBoosterIcon: class extends self.ISpriteInstance {},
	StartBoosterButton: class extends self.ISpriteInstance {},
	TimesUpText: class extends self.ITextInstance {},
	TimesUpText2: class extends self.ITextInstance {},
	RoadSegment0: class extends self.ITiledBackgroundInstance {},
	RoadSegment1: class extends self.ITiledBackgroundInstance {},
	RoadSegment2: class extends self.ITiledBackgroundInstance {},
	RoadSegment3: class extends self.ITiledBackgroundInstance {},
	RoadSegment4: class extends self.ITiledBackgroundInstance {},
	RoadSegment5: class extends self.ITiledBackgroundInstance {},
	RoadSegment6: class extends self.ITiledBackgroundInstance {},
	RoadSegment7: class extends self.ITiledBackgroundInstance {},
	RoadSegment8: class extends self.ITiledBackgroundInstance {},
	RoadSegment9: class extends self.ITiledBackgroundInstance {},
	RoadSegment10: class extends self.ITiledBackgroundInstance {},
	RoadSegment11: class extends self.ITiledBackgroundInstance {},
	RoadSegment12: class extends self.ITiledBackgroundInstance {},
	RoadSegment13: class extends self.ITiledBackgroundInstance {},
	RoadSegment14: class extends self.ITiledBackgroundInstance {},
	RoadSegment15: class extends self.ITiledBackgroundInstance {},
	RoadSegment16: class extends self.ITiledBackgroundInstance {},
	RoadSegment17: class extends self.ITiledBackgroundInstance {},
	RoadSegment18: class extends self.ITiledBackgroundInstance {},
	RoadSegment19: class extends self.ITiledBackgroundInstance {},
	RoadSegment20: class extends self.ITiledBackgroundInstance {},
	RoadSegment21: class extends self.ITiledBackgroundInstance {},
	RoadSegment22: class extends self.ITiledBackgroundInstance {},
	RoadSegment23: class extends self.ITiledBackgroundInstance {},
	RoadSegment24: class extends self.ITiledBackgroundInstance {},
	RoadSegment25: class extends self.ITiledBackgroundInstance {},
	Checkpoint: class extends self.ISpriteInstance {},
	StartCheckpoint: class extends self.ISpriteInstance {},
	OtherCar: class extends self.ISpriteInstance {},
	OtherCar2: class extends self.ISpriteInstance {},
	DestroyEffect: class extends self.ISpriteInstance {},
	CoinCollectEffect: class extends self.IParticlesInstance {},
	OtherCar3: class extends self.ISpriteInstance {},
	NarrowRoad: class extends self.ITiledBackgroundInstance {},
	Road_Y: class extends self.ISpriteInstance {},
	Road: class extends self.ITiledBackgroundInstance {},
	Road_Y2: class extends self.ISpriteInstance {},
	RoadWide: class extends self.ITiledBackgroundInstance {},
	RoadEnd: class extends self.ISpriteInstance {},
	RoadX: class extends self.ISpriteInstance {},
	Coin1Pickup: class extends self.ISpriteInstance {},
	TimePickup: class extends self.ISpriteInstance {},
	MusicToggle: class extends self.ISpriteInstance {},
	SoundsToggle: class extends self.ISpriteInstance {},
	ButtonSmallBlackText: class extends self.ITextInstance {},
	Logo: class extends self.ISpriteInstance {},
	MenuCheckpointsText: class extends self.ITextInstance {},
	MenuCoinsText: class extends self.ITextInstance {},
	HeaderText: class extends self.ITextInstance {},
	BackToMenuButtonOld: class extends self.IWorldInstance {},
	EndRaceText: class extends self.ITextInstance {},
	SelectCarButton: class extends self.IWorldInstance {},
	ButtonSmallText: class extends self.ITextInstance {},
	MenuCoinsIcon: class extends self.ISpriteInstance {},
	MenuCheckpointsIcon: class extends self.ISpriteInstance {},
	MenuSelectedCar0: class extends self.ISpriteInstance {},
	MenuSelectedCar1: class extends self.ISpriteInstance {},
	MenuSelectedCar2: class extends self.ISpriteInstance {},
	MenuSelectedCar3: class extends self.ISpriteInstance {},
	MenuSelectedCar4: class extends self.ISpriteInstance {},
	MenuSelectedCar5: class extends self.ISpriteInstance {},
	MenuSelectedCar6: class extends self.ISpriteInstance {},
	MenuSelectedCar7: class extends self.ISpriteInstance {},
	PausePanel: class extends self.IWorldInstance {},
	EndRaceText2: class extends self.ITextInstance {},
	MenuBoosterStatusText: class extends self.ITextInstance {},
	CarNameText: class extends self.ITextInstance {},
	CarDetailsLabelText: class extends self.ITextInstance {},
	CarDetailsText: class extends self.ITextInstance {},
	CarCostText: class extends self.ITextInstance {},
	ShopActiveCar: class extends self.IWorldInstance {},
	ShopActiveCarText: class extends self.ITextInstance {},
	ButtonText: class extends self.ITextInstance {},
	PanelText: class extends self.ITextInstance {},
	ErrorText: class extends self.ITextInstance {},
	TermsText: class extends self.ITextInstance {},
	UserNameText: class extends self.ITextInstance {},
	GameplaysText: class extends self.ITextInstance {},
	TotalScoreText: class extends self.ITextInstance {},
	LeaderboardEntryText: class extends self.ITextInstance {},
	ProfilName: class extends self.ITextInstance {},
	BackToMenuButton2: class extends self.IWorldInstance {},
	BackToMenuButton3: class extends self.IWorldInstance {},
	BackToMenuButton4: class extends self.IWorldInstance {},
	WaitHeaderText: class extends self.ITextInstance {},
	SelectCarButton2: class extends self.IWorldInstance {},
	SelectCarButton3: class extends self.IWorldInstance {},
	SelectCarButton4: class extends self.IWorldInstance {},
	SelectCarButton5: class extends self.IWorldInstance {},
	SelectCarButton6: class extends self.IWorldInstance {},
	WaitPanel: class extends self.IWorldInstance {},
	WaitText: class extends self.ITextInstance {},
	WaitErrorText: class extends self.ITextInstance {},
	PlayButton: class extends self.ISpriteInstance {},
	ProfileButton: class extends self.ISpriteInstance {},
	LeaderboardButton: class extends self.ISpriteInstance {},
	ReadyButton: class extends self.ISpriteInstance {},
	StartButton: class extends self.ISpriteInstance {},
	CloseEditingNameButton: class extends self.ISpriteInstance {},
	ChangeNameButton: class extends self.ISpriteInstance {},
	LeaderboardEntryPointsText: class extends self.ITextInstance {},
	AvailableMintsText: class extends self.ITextInstance {},
	CreateAccountButton: class extends self.ISpriteInstance {},
	TokenCost: class extends self.ITextInstance {},
	MenuOtherCar: class extends self.ISpriteInstance {},
	MenuOtherCar2: class extends self.ISpriteInstance {},
	MenuOtherCar3: class extends self.ISpriteInstance {},
	MenuOtherCar4: class extends self.ISpriteInstance {},
	MenuOtherCar5: class extends self.ISpriteInstance {},
	MenuOtherCar6: class extends self.ISpriteInstance {},
	MenuRoad: class extends self.ITiledBackgroundInstance {},
	MenuTunnel: class extends self.ISpriteInstance {},
	Lake: class extends self.ISpriteInstance {},
	SummaryRaceCoins: class extends self.ITextInstance {},
	SummaryRacePoints: class extends self.ITextInstance {},
	SummaryTopText: class extends self.ITextInstance {},
	SummaryTotalCoins: class extends self.ITextInstance {},
	SummaryTotalPoints: class extends self.ITextInstance {},
	SummaryRestartButton: class extends self.IWorldInstance {},
	SummaryOKButton: class extends self.ISpriteInstance {},
	ReferralCodeText: class extends self.ITextInstance {},
	ReferralCodeTextInput: class extends self.ITextInputInstance {},
	TermsCheckbox: class extends self.ISpriteInstance {},
	NameInput: class extends self.ITextInputInstance {},
	CopyCode: class extends self.ISpriteInstance {},
	EditNameButton: class extends self.ISpriteInstance {},
	FriendsButton: class extends self.IButtonInstance {},
	FriendsCode: class extends self.ITextInstance {},
	FriendsLevelText: class extends self.ITextInstance {},
	FriendsPercentageText: class extends self.ITextInstance {},
	FriendsPointsText: class extends self.ITextInstance {},
	FriendsUserCountText: class extends self.ITextInstance {},
	LeaderboardRefNicknameText: class extends self.ITextInstance {},
	LeaderboardRefPointsText: class extends self.ITextInstance {},
	LeaderboardStart: class extends self.ISpriteInstance {},
	ReferralsList: class extends self.ITextInstance {},
	ShareLink: class extends self.ISpriteInstance {},
	ShopDebugText: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	BuyBoosterWithCoinsButton: class extends self.ISpriteInstance {},
	BuyBoosterWithTokenButton: class extends self.ISpriteInstance {},
	LeaderboardPointsStart: class extends self.ISpriteInstance {},
	LeaderboardStart2: class extends self.ISpriteInstance {},
	LeaderboardPointsStart2: class extends self.ISpriteInstance {},
	ButtonNext: class extends self.ISpriteInstance {},
	ButtonPrev: class extends self.ISpriteInstance {},
	PauseMusicButton: class extends self.ISpriteInstance {},
	PauseSoundsButton: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	MenuBg: class extends self.ISpriteInstance {},
	MiddlePanel: class extends self.ISpriteInstance {},
	ShopSetCurrentButton: class extends self.ISpriteInstance {},
	ShopBuyButton: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	MetaproPlugin: class extends self.IInstance {},
	Avatar_Profile_Main: class extends self.IHTMLElementInstance {},
	LoginButton: class extends self.ISpriteInstance {},
	ChangeCarButton: class extends self.ISpriteInstance {},
	BackButton: class extends self.ISpriteInstance {},
	Arrow_Right067x: class extends self.ISpriteInstance {},
	InputBackground: class extends self.ISpriteInstance {},
	BackToMenuButton: class extends self.ISpriteInstance {},
	PauseResumeButton: class extends self.ISpriteInstance {},
	PauseEndRaceButton: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	TargetCircle: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Cars: class extends self.ISpriteInstance {},
	Segments: class extends self.ITiledBackgroundInstance {},
	Obstacles: class extends self.ISpriteInstance {},
	FadeIn: class extends self.ITextInstance {},
	ShopCars: class extends self.ISpriteInstance {}
}